name: Release Automation

on:
  push:
    branches:
      - main

permissions:
  contents: write # Grant write access to push tags

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Bump version and push tag
        id: bump
        uses: anothrNick/github-tag-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch # Can be major, minor, or patch
          initial_version: 0.1.0 # Set an initial version if no tags exist

      - name: Create GitHub release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.bump.outputs.new_tag }}
          release_name: Release ${{ steps.bump.outputs.new_tag }}
          body: |
            Automated release created via GitHub Actions.
          draft: false
          prerelease: false
